CRITICAL - 2023-03-09 14:15:04 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\prueba_usuarios\system\Database\Config.php(78): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-09 14:16:13 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\prueba_usuarios\system\Database\Config.php(78): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-09 14:18:23 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\prueba_usuarios\system\Database\Config.php(78): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-09 14:18:53 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\prueba_usuarios\system\Database\Config.php(78): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-09 14:20:43 -->  is not a valid database connection group.
#0 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('')
#1 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#2 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-03-09 14:21:31 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\prueba_usuarios\system\Database\Config.php(78): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\prueba_usuarios\system\Model.php(97): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\prueba_usuarios\app\Models\UsersModel.php(13): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(28): App\Models\UsersModel->__construct()
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-03-09 14:54:24 --> Call to undefined function App\Controllers\perform_http_request()
#0 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-03-09 15:03:53 --> Call to undefined function App\Controllers\print_t()
#0 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-03-09 15:09:07 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:09:07 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:09:44 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:09:44 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:10:15 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:10:15 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:10:52 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:10:52 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:11:38 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:11:38 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:14:30 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:14:30 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:19:21 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:19:21 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:20:35 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:20:51 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:20:51 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:21:25 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(34): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:21:25 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:22:47 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(33): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:22:47 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:28:04 --> Use of undefined constant CURLOPT_GET - assumed 'CURLOPT_GET' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 46, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 15:28:04 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:28:27 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:28:27 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:34:16 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:34:16 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp\htdocs\prueba_usuarios\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(342): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp\htdocs\prueba_usuarios\system\Debug\Exceptions.php(115): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\HTTP\Exceptions\HTTPException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2023-03-09 15:35:39 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:36:24 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:36:31 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:37:17 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:37:46 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:39:14 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:39:37 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:42:55 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:43:42 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...', Array)
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 15:43:54 --> 22 : The requested URL returned error: 403 
#0 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(656): CodeIgniter\HTTP\Exceptions\HTTPException::forCurlError('22', 'The requested U...')
#1 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(364): CodeIgniter\HTTP\CURLRequest->sendRequest(Array)
#2 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(140): CodeIgniter\HTTP\CURLRequest->send('get', 'https://api.git...')
#3 C:\xampp\htdocs\prueba_usuarios\system\HTTP\CURLRequest.php(170): CodeIgniter\HTTP\CURLRequest->request('get', 'https://api.git...', Array)
#4 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\HTTP\CURLRequest->get('https://api.git...')
#5 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#6 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#7 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-03-09 16:02:57 --> Use of undefined constant items - assumed 'items' (this will throw an Error in a future version of PHP)
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Use of undefine...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 16:06:40 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(47): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 47, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 16:08:21 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(47): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 47, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:20:37 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:20:40 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:20:40 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:20:44 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:21:15 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:22:16 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 17:29:50 --> Undefined variable: users_model
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 42, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 18:05:30 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(43): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 43, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 18:07:15 --> file_get_contents(people.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 43, Array)
#1 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(43): file_get_contents('people.json')
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2023-03-09 18:07:28 --> file_get_contents(people.json): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'C:\\xampp\\htdocs...', 43, Array)
#1 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(43): file_get_contents('people.json')
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2023-03-09 18:10:46 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 45, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-03-09 18:12:27 --> Trying to get property 'items' of non-object
#0 C:\xampp\htdocs\prueba_usuarios\app\Controllers\Users.php(45): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 45, Array)
#1 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(832): App\Controllers\Users->searchUsers()
#2 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\prueba_usuarios\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\prueba_usuarios\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
